### ISSUE TITLE
Default language is set to Italian

### ISSUE THREAD

**Issue by hsingfoo** [innovyou/ns8-odoo#9]
Hi,

Currently the default language is set to Italian and only the Italian language pack is loaded. It would be nice and good practice, looking at the NS7/8 community, to set the default language to English

TIA

**Comment by GPaolo8** [comment]
Hi @hsingfoo tank you for the notification. 

We are going to release English language pack next week.

Have a good day

**Comment by hsingfoo** [comment]
Hi @GPaolo8 , I was wondering if the Odoo app got released at all at this time please?

**Comment by GPaolo8** [comment]
HI @hsingfoo the latest version (1.0.2) of Odoo app has been released
